services:
  microservicio-servicios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio_servicios
    network_mode: host
    restart: unless-stopped
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 10.43.103.40:9092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: 10.43.103.40:9092
